### ISSUE TITLE
Submission checklist

### ISSUE THREAD

**Issue by earowang** [earowang/thesis#5]
- [x] update contribution table in declaration
- [x] make sure the appendix title
- [x] update description: all the packages used for the thesis, along with their version numbers
- [x] check requirement for preliminary pages
- [x] check figures/tables in the right positions
- [x] check citations
- [x] generate `renv.lock` for reproducing it later, mentioning `renv` in the readme
- [x] bump version to `v1.0.0` and release
